[cdr]
cdr_path="data/cdr.log"

[logo]
logo='data/logo_horus.png'

[master]
name='MASTER'
username='a'
password='a'
email='gh@gmai.com'

[connections.mysql]
dialect = "mysql"
host = "localhost"
port = 3306
database = "dashboard_database"
username = "root"
password = "admin"
query = { charset = "utf8" }

[cookie]
name='my_cookie'